### PR TITLE
summit level writeup

### PR DESCRIPTION
**Pull request by AnshumanNeon**
added and wrote summit level write in design/design_summit.md

### CODE REVIEW

**Comment by Calverin** [comment]
I've left some comments in #newleste-p8 in the Discord. Great work so far though!

**Comment by Antibrain0** [comment]
These are some really good levels! Be sure to read cal's comments in #newleste-p8 on the discord.

Some screenshots do appear to be cut off, unsure whether this is unintentional or not.

I am not a project manager, or at least don't view myself to be one, so i'll hold off on reviewing this PR until a project manager reviews it.

Thank you for your work so far!

**Comment by AnshumanNeon** [comment]
thnx guys, i'm still working on this. looking for full images of rooms

**Review by Calverin — APPROVED** [review]
All looks good to me! If issues are found with specific level choices later on they can be managed as they pop up but as none of the other reviewers have said anything I'll approve it for now. Nicely done!

**Pull request merged**
